name: CI Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Smoke test
        run: npm run smoke
        env:
          SMOKE_HOST: 127.0.0.1
          SMOKE_PORT: 5180
          SMOKE_TIMEOUT_MS: 30000

      - name: Unit tests
        run: npm test -- --runInBand

      - name: Route smoke
        run: npm run smoke:routes
